name: suyog_chess_sc
description: 'A comprehensive Flutter Chess game with enhanced features.'
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  confetti: ^0.8.0
  audioplayers: ^6.1.0
  shared_preferences: ^2.3.3
  http: ^1.1.0   # 👈 Extra in this version

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/images/
    - assets/sounds/